# Generated by Django 4.1.7 on 2023-03-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230329_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='description',
            new_name='descrption',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='descrption',
            new_name='description',
        ),
    ]
